<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <None Include="LIT.TopSpecs.Aspire.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LIT.TopSpecs.Aspire.ServiceDefaults\LIT.TopSpecs.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\LIT.TopSpecs.SharedKernel\LIT.TopSpecs.SharedKernel.csproj" />
    <ProjectReference Include="..\LIT.TopSpecs.Web.Client\LIT.TopSpecs.Web.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

</Project>
