<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>1cd3e022-dc33-4f37-9323-4407b7198b63</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LIT.TopSpecs.ApiService\LIT.TopSpecs.Aspire.ApiService.csproj" />
    <ProjectReference Include="..\LIT.TopSpecs.Web\LIT.TopSpecs.Aspire.Web.csproj" />
  </ItemGroup>

</Project>
